--  Consultas proyecto 

--2.1 
--Insertar 3 registros en:

--TipoContacto 

INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) 
VALUES ('CEL', 'TELEFONO CELULAR');

INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) 
VALUES ('EMA', 'CORREO ELECTRONICO');

INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) 
VALUES ('DIR', 'DIRECCION NOTIFICACION');

--TipoDocumento

INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC)
VALUES ('CC', 'CEDULA DE CIUDADANIA');

INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC)
VALUES ('TI', 'TARJETA DE IDENTIDAD');

INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC)
VALUES ('CE', 'CEDULA DE EXTRANJERIA');

--TipoLugar 

INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) 
VALUES ('JUZG', 'JUZGADO');

INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) 
VALUES ('CIUD', 'CIUDAD');

INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) 
VALUES ('TRIB', 'TRIBUNAL');

--FormaPago

INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) 
VALUES ('EFE', 'EFECTIVO');

INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) 
VALUES ('TAR', 'TARJETA CRED O DEB');

INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) 
VALUES ('CHE', 'CHEQUE');

--Franquicia 
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) 
VALUES ('VIS', 'VISA');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) 
VALUES ('MAS', 'MASTERCARD');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) 
VALUES ('AME', 'AMERICAN EXPRESS');

--2.2

--Especializaciones

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('PEN', 'PENAL');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('CIV', 'CIVIL');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('LAB', 'LABORAL');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('ADM', 'ADMINISTRATIVO');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('TUT', 'TUTELA');

--Etapas Procesales

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) 
VALUES ('IND', 'INDAGACION');

INSERT INTO ETAPAPROCESAL(CODETAPA, NOMETAPA)
VALUES ('IPN','IMPUTACION');



INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA)
VALUES('ACU','ACUSACION');  

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA)
VALUES('JUI','JUICIO');

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA)
VALUES('SEN','SENTENCIA');

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA)
VALUES('IMP','IMPUGNACION');

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA)
VALUES ('DEM', 'DEMANDA');

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA)
VALUES ('CON', 'CONTESTACION');

INSERT INTO ETAPAPROCESAL(CODETAPA, NOMETAPA)
VALUES ('AUD','AUDIENCIA');

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA)
VALUES('PRU','PRUEBAS');

INSERT INTO ETAPAPROCESAL(CODETAPA, NOMETAPA)
VALUES ('PRE','PRESENTACION');

INSERT INTO ETAPAPROCESAL(CODETAPA, NOMETAPA)
VALUES ('TRA', 'TRÁMITE URGENTE');

INSERT INTO ETAPAPROCESAL(CODETAPA, NOMETAPA)
VALUES ('FAL', 'FALLO');

--Impugnaciones


INSERT INTO IMPUGNACION(IDIMPUGNA, NOMIMPUGNA)
VALUES ('RP', 'REPOSICIÓN');

INSERT INTO IMPUGNACION(IDIMPUGNA, NOMIMPUGNA)
VALUES ('AP', 'APELACIÓN');

INSERT INTO IMPUGNACION(IDIMPUGNA, NOMIMPUGNA)
VALUES ('CA', 'CASACIÓN');

INSERT INTO IMPUGNACION(IDIMPUGNA, NOMIMPUGNA)
VALUES ('RV', 'REVISION');

INSERT INTO IMPUGNACION(IDIMPUGNA, NOMIMPUGNA)
VALUES ('UJ', 'UNIFICACIÓN DE JURISPRUDENCIA');

INSERT INTO IMPUGNACION(IDIMPUGNA, NOMIMPUGNA)
VALUES ('IM', 'IMPUGNACION DE TUTELA');

INSERT INTO IMPUGNACION(IDIMPUGNA, NOMIMPUGNA)
VALUES ('RC', 'REVISIÓN CONSTITUCIONAL');

--2.3 
--Especia-etapa : Todos las Especializaciones 
--con todas las posibles etapas, impugnaciones e instancias

---- Instancias


INSERT INTO INSTANCIA(NINSTANCIA)
VALUES (1);

INSERT INTO INSTANCIA(NINSTANCIA)
VALUES (2);

INSERT INTO INSTANCIA (NINSTANCIA) VALUES (3);


---- Especia_etapa

---- PENAL
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',1,1,'IND',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',2,1,'IPN',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',3,1,'ACU',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',4,1,'JUI',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',5,1,'SEN',NULL);

-- Impugnaciones
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',6,2,'IPG','RP');
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',6,2,'IPG','AP');
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',6,2,'IPG','CA');
INSERT INTO ESPECIA_ETAPA VALUES ('PEN',6,2,'IPG','RV');

---- CIVIL
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',1,1,'DEM',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',2,1,'CON',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',3,1,'AUD',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',4,1,'PRU',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',5,1,'SEN',NULL);
-- Impugnaciones
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',6,2,'IPG','RP');
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',6,2,'IPG','AP');
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',6,2,'IPG','CA');
INSERT INTO ESPECIA_ETAPA VALUES ('CIV',6,2,'IPG','RV');

---- LABORAL
INSERT INTO ESPECIA_ETAPA VALUES ('LAB',1,1,'DEM',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('LAB',2,1,'AUD',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('LAB',3,1,'PRU',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('LAB',4,1,'SEN',NULL);
-- Impugnaciones
INSERT INTO ESPECIA_ETAPA VALUES ('LAB',5,2,'IPG','AP');
INSERT INTO ESPECIA_ETAPA VALUES ('LAB',5,2,'IPG','CA');

---- ADMINISTRATIVO 
INSERT INTO ESPECIA_ETAPA VALUES ('ADM',1,1,'DEM',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('ADM',2,1,'CON',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('ADM',3,1,'PRU',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('ADM',4,1,'SEN',NULL);
-- Impugnaciones
INSERT INTO ESPECIA_ETAPA VALUES ('ADM',5,2,'IPG','AP');
INSERT INTO ESPECIA_ETAPA VALUES ('ADM',5,2,'IPG','RV');
INSERT INTO ESPECIA_ETAPA VALUES ('ADM',5,2,'IPG','UJ');

--- FAMILIA
INSERT INTO ESPECIA_ETAPA VALUES ('FAM',1,1,'DEM',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('FAM',2,1,'AUD',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('FAM',3,1,'PRU',NULL);
INSERT INTO ESPECIA_ETAPA VALUES ('FAM',4,1,'SEN',NULL);
-- Impugnaciones
INSERT INTO ESPECIA_ETAPA VALUES ('FAM',5,2,'IPG','AP');
INSERT INTO ESPECIA_ETAPA VALUES ('FAM',5,2,'IPG','CA');

---- TUTELA
INSERT INTO ESPECIA_ETAPA VALUES ('TUT',1,1,'PRE',NULL);  -- Presentación
INSERT INTO ESPECIA_ETAPA VALUES ('TUT',2,1,'TRA',NULL);  -- Trámite urgente
INSERT INTO ESPECIA_ETAPA VALUES ('TUT',3,1,'FAL',NULL);  -- Fallo
-- Impugnaciones
INSERT INTO ESPECIA_ETAPA VALUES ('TUT',4,2,'IPG','IM');
INSERT INTO ESPECIA_ETAPA VALUES ('TUT',4,2,'IPG','RC');

---2.4 Insertar 5 cleintes y 5 abogados

---- CLIENTE
INSERT INTO CLIENTE VALUES ('00001','JULIAN','CELIS',5104895);  
INSERT INTO CLIENTE VALUES ('00002','CRISTIAN','LOPEZ',1021544);  
INSERT INTO CLIENTE VALUES ('00003','CARLOS','BARRIGA',1057891);  
INSERT IINTO LIENTE VALUES ('00004','SANTIAGO','PARDO',1001325);
INSERT IINTO LIENTE VALUES ('00005','DAVID','GIRALDO',2004789);

---- ABOGADO 
INSERT INTO ABOGADO VALUES ('7894561' ,'JULIAN','CELIS',5104895);  
INSERT INTO ABOGADO VALUES ('1234567','CRISTIAN','LOPEZ',1021544);  
INSERT INTO ABOGADO VALUES ('3216547','CARLOS','BARRIGA',1057891);  
INSERT INTO ABOGADO VALUES ('9876541','SANTIAGO','PARDO',1001325);
INSERT INTO ABOGADO VALUES ('6549873','DAVID','GIRALDO',2004789);