--  Consultas proyecto 

--2.1 
--Insertar 3 registros en:

--TipoContacto 

INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) 
VALUES ('CEL', 'TELEFONO CELULAR');

INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) 
VALUES ('EMA', 'CORREO ELECTRONICO');

INSERT INTO TIPOCONTACT (IDTIPOCONTA, DESCTIPOCONTA) 
VALUES ('DIR', 'DIRECCION NOTIFICACION');

--TipoDocumento

INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC)
VALUES ('CC', 'CEDULA DE CIUDADANIA');

INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC)
VALUES ('TI', 'TARJETA DE IDENTIDAD');

INSERT INTO TIPODOCUMENTO (IDTIPODOC, DESCTIPODOC)
VALUES ('CE', 'CEDULA DE EXTRANJERIA');

--TipoLugar 

INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) 
VALUES ('JUZG', 'JUZGADO');

INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) 
VALUES ('CIUD', 'CIUDAD');

INSERT INTO TIPOLUGAR (IDTIPOLUGAR, DESCTIPOLUGAR) 
VALUES ('TRIB', 'TRIBUNAL');

--FormaPago

INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) 
VALUES ('EFE', 'EFECTIVO');

INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) 
VALUES ('TAR', 'TARJETA CRED O DEB');

INSERT INTO FORMAPAGO (IDFORMAPAGO, DESCFORMAPAGO) 
VALUES ('CHE', 'CHEQUE');

--Franquicia 
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) 
VALUES ('VIS', 'VISA');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) 
VALUES ('MAS', 'MASTERCARD');
INSERT INTO FRANQUICIA (CODFRANQUICIA, NOMFRANQUICIA) 
VALUES ('AME', 'AMERICAN EXPRESS');

--2.2

--Especializaciones

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('PEN', 'PENAL');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('CIV', 'CIVIL');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('LAB', 'LABORAL');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('ADM', 'ADMINISTRATIVO');

INSERT INTO ESPECIALIZACION (CODESPECIALIZACION, NOMESPECIALIZACION) 
VALUES ('TUT', 'TUTELA');

--Etapas Procesales

INSERT INTO ETAPAPROCESAL (CODETAPA, NOMETAPA) 
VALUES ('IND', 'INDAGACION');





